etce_bbcnews_homepage:
    path:     /bbc/{name}
    defaults: { _controller: EtceBbcnewsBundle:Default:index }
etce_bbcnews_redis:
    path:     /redis
    defaults: { _controller: EtceBbcnewsBundle:Default:redis }
