services:
    etce_bbcnews.guzzle:
        class: GuzzleHttp\Client
#        arguments: [@service_id, "plain_value", %parameter%]
    json_exception_listener:
        class: Etce\BbcnewsBundle\Listeners\JsonExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 200 }
